apiVersion: v1
kind: Service
metadata:
    name: order
    labels:
        name: order
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
    selector:
        app: auth